"""Entity device-class mappings for sensors, numbers, and binary sensors."""

from homeassistant.components.binary_sensor import (
    BinarySensorDeviceClass as _BinarySensorDeviceClass,
)
from homeassistant.components.number import NumberDeviceClass as _NumberDeviceClass
from homeassistant.components.sensor import SensorDeviceClass as _SensorDeviceClass

ENTITY_SENSOR_DEVICE_CLASS_MAP: dict[str, _SensorDeviceClass | None] = {
    "tempFeeder": _SensorDeviceClass.TEMPERATURE,
    "tempExternalSensor": _SensorDeviceClass.TEMPERATURE,
    "tempCO": _SensorDeviceClass.TEMPERATURE,
    "tempCOSet": _SensorDeviceClass.TEMPERATURE,
    "boilerPower": _SensorDeviceClass.POWER_FACTOR,
    "boilerPowerKW": _SensorDeviceClass.POWER,
    "fanPower": _SensorDeviceClass.POWER_FACTOR,
    "tempFlueGas": _SensorDeviceClass.TEMPERATURE,
    "mixerSetTemp1": _SensorDeviceClass.TEMPERATURE,
    "mixerSetTemp2": _SensorDeviceClass.TEMPERATURE,
    "mixerSetTemp3": _SensorDeviceClass.TEMPERATURE,
    "mixerSetTemp4": _SensorDeviceClass.TEMPERATURE,
    "mixerSetTemp5": _SensorDeviceClass.TEMPERATURE,
    "mixerSetTemp6": _SensorDeviceClass.TEMPERATURE,
    "mixerTemp1": _SensorDeviceClass.TEMPERATURE,
    "mixerTemp2": _SensorDeviceClass.TEMPERATURE,
    "mixerTemp3": _SensorDeviceClass.TEMPERATURE,
    "mixerTemp4": _SensorDeviceClass.TEMPERATURE,
    "mixerTemp5": _SensorDeviceClass.TEMPERATURE,
    "mixerTemp6": _SensorDeviceClass.TEMPERATURE,
    "mixerTemp": _SensorDeviceClass.TEMPERATURE,
    "mixerSetTemp": _SensorDeviceClass.TEMPERATURE,
    "tempBack": _SensorDeviceClass.TEMPERATURE,
    "tempCWU": _SensorDeviceClass.TEMPERATURE,
    "statusCO": _SensorDeviceClass.ENUM,
    "statusCWU": None,
    "tempUpperBuffer": _SensorDeviceClass.TEMPERATURE,
    "tempLowerBuffer": _SensorDeviceClass.TEMPERATURE,
    "signal": _SensorDeviceClass.SIGNAL_STRENGTH,
    "servoMixer1": _SensorDeviceClass.ENUM,
    "mode": _SensorDeviceClass.ENUM,
    "transmission": _SensorDeviceClass.ENUM,
    # ecoMAX850R2-X specific device classes
    "fuelConsum": _SensorDeviceClass.POWER_FACTOR,
    # fuelStream: No device class - HA has no SensorDeviceClass for mass flow rate (kg/h)
    # ecoSTER thermostat device classes
    "ecoSterTemp1": _SensorDeviceClass.TEMPERATURE,
    "ecoSterTemp2": _SensorDeviceClass.TEMPERATURE,
    "ecoSterTemp3": _SensorDeviceClass.TEMPERATURE,
    "ecoSterTemp4": _SensorDeviceClass.TEMPERATURE,
    "ecoSterTemp5": _SensorDeviceClass.TEMPERATURE,
    "ecoSterTemp6": _SensorDeviceClass.TEMPERATURE,
    "ecoSterTemp7": _SensorDeviceClass.TEMPERATURE,
    "ecoSterTemp8": _SensorDeviceClass.TEMPERATURE,
    "ecoSterSetTemp1": _SensorDeviceClass.TEMPERATURE,
    "ecoSterSetTemp2": _SensorDeviceClass.TEMPERATURE,
    "ecoSterSetTemp3": _SensorDeviceClass.TEMPERATURE,
    "ecoSterSetTemp4": _SensorDeviceClass.TEMPERATURE,
    "ecoSterSetTemp5": _SensorDeviceClass.TEMPERATURE,
    "ecoSterSetTemp6": _SensorDeviceClass.TEMPERATURE,
    "ecoSterSetTemp7": _SensorDeviceClass.TEMPERATURE,
    "ecoSterSetTemp8": _SensorDeviceClass.TEMPERATURE,
    "ecoSterMode1": None,
    "ecoSterMode2": None,
    "ecoSterMode3": None,
    "ecoSterMode4": None,
    "ecoSterMode5": None,
    "ecoSterMode6": None,
    "ecoSterMode7": None,
    "ecoSterMode8": None,
    # ecoMAX360i
    "Circuit2thermostatTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit3thermostatTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit4thermostatTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit5thermostatTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit6thermostatTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit7thermostatTemp": _SensorDeviceClass.TEMPERATURE,
    "TempClutch": _SensorDeviceClass.TEMPERATURE,
    "TempWthr": _SensorDeviceClass.TEMPERATURE,
    "TempCircuit2": _SensorDeviceClass.TEMPERATURE,
    "TempCircuit3": _SensorDeviceClass.TEMPERATURE,
    "TempCircuit4": _SensorDeviceClass.TEMPERATURE,
    "TempCircuit5": _SensorDeviceClass.TEMPERATURE,
    "TempCircuit6": _SensorDeviceClass.TEMPERATURE,
    "TempCircuit7": _SensorDeviceClass.TEMPERATURE,
    "TempBuforUp": _SensorDeviceClass.TEMPERATURE,
    "TempCWU": _SensorDeviceClass.TEMPERATURE,
    "TempBuforDown": _SensorDeviceClass.TEMPERATURE,
    "heatingUpperTemp": _SensorDeviceClass.TEMPERATURE,
    # Circuit1thermostat is a thermostat state (no "Temp" suffix), not a temperature.
    "Circuit1thermostat": None,
    "flapValveStates": _SensorDeviceClass.ENUM,
    "HeatDemanded": _SensorDeviceClass.ENUM,
    "WaterPumpRunning": _SensorDeviceClass.ENUM,
    # Heat pump (Axen) device classes
    "AxenOutdoorTemp": _SensorDeviceClass.TEMPERATURE,
    "AxenOutgoingTemp": _SensorDeviceClass.TEMPERATURE,
    "AxenReturnTemp": _SensorDeviceClass.TEMPERATURE,
    "AxenCompressorFreq": _SensorDeviceClass.FREQUENCY,
    "AxenUpperPump": None,
    "AxenWorkState": None,
    "HeatSourceCalcPresetTemp": _SensorDeviceClass.TEMPERATURE,
    # Heat pump compressor temperature device classes
    "afterCompressorTemp": _SensorDeviceClass.TEMPERATURE,
    "beforeCompressorTemp": _SensorDeviceClass.TEMPERATURE,
    "exhaustGasTemp": _SensorDeviceClass.TEMPERATURE,
    "outdoorTemp": _SensorDeviceClass.TEMPERATURE,
    # Heat pump status device classes
    "HPStatusWorkMode": None,
    "HPStatusPresetTemp": _SensorDeviceClass.TEMPERATURE,
    "HPStatusControl": None,
    # SSA (weather compensation) device classes
    "ssaState": None,
    "ssaCorr": _SensorDeviceClass.TEMPERATURE,
    "ssaPrevTemp": _SensorDeviceClass.TEMPERATURE,
    # Circuit comfort/eco temperature device classes
    "Circuit1ComfortTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit1EcoTemp": _SensorDeviceClass.TEMPERATURE,
    "BufferTargetTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit2ComfortTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit2EcoTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit3ComfortTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit3EcoTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit4ComfortTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit4EcoTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit5ComfortTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit5EcoTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit6ComfortTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit6EcoTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit7ComfortTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit7EcoTemp": _SensorDeviceClass.TEMPERATURE,
    # ecoMAX360i informationParams / editParams device classes
    "TargetFlowTemp": _SensorDeviceClass.TEMPERATURE,
    "ActualFlowTemp": _SensorDeviceClass.TEMPERATURE,
    "ActualReturnTemp": _SensorDeviceClass.TEMPERATURE,
    "FanSpeed": None,
    "HeatPumpAmbient": _SensorDeviceClass.TEMPERATURE,
    "ActualDHWTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit1DesiredLWT": _SensorDeviceClass.TEMPERATURE,
    "ElectricalPower": _SensorDeviceClass.POWER,
    "ThermalPower": _SensorDeviceClass.POWER,
    "COP": _SensorDeviceClass.POWER_FACTOR,
    "SCOP": _SensorDeviceClass.POWER_FACTOR,
    "FlowRate": None,
    "AXENREGISTER64": None,
    "AXENREGISTER65": None,
    # Phoenix / extended heat-pump device classes (decomposed from EXTRA_SENSORS)
    "BuforCalcSetTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit1CalcTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit2CalcTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit4CalcTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit5CalcTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit6CalcTemp": _SensorDeviceClass.TEMPERATURE,
    "Circuit7CalcTemp": _SensorDeviceClass.TEMPERATURE,
    "HDWsetpointcalculate": _SensorDeviceClass.TEMPERATURE,
    "CoolingPower": _SensorDeviceClass.POWER,
    "HeatingPower": _SensorDeviceClass.POWER,
    "ElectricPower": _SensorDeviceClass.POWER,
    "PHNXcoil_temp": _SensorDeviceClass.TEMPERATURE,
    "PHNXdischarge_temp": _SensorDeviceClass.TEMPERATURE,
    "PHNXinletTemp": _SensorDeviceClass.TEMPERATURE,
    "PHNXinletTemp_pump": _SensorDeviceClass.TEMPERATURE,
    "PHNXinletTemp_pump2": _SensorDeviceClass.TEMPERATURE,
    "PHNXinletTemp_pump3": _SensorDeviceClass.TEMPERATURE,
    "PHNXinletTemp_pump5": _SensorDeviceClass.TEMPERATURE,
    "PHNXoutletTemp": _SensorDeviceClass.TEMPERATURE,
    "PHNXoutletTemp_pump2": _SensorDeviceClass.TEMPERATURE,
    "PHNXoutletTemp_pump3": _SensorDeviceClass.TEMPERATURE,
    "PHNXoutletTemp_pump4": _SensorDeviceClass.TEMPERATURE,
    "PHNXoutletTemp_pump5": _SensorDeviceClass.TEMPERATURE,
    "PHNXreg2045": _SensorDeviceClass.TEMPERATURE,
    "PHNXreg2046": _SensorDeviceClass.TEMPERATURE,
    "PHNXreg2071": _SensorDeviceClass.FREQUENCY,
    "PHNXsuctionTemp": _SensorDeviceClass.TEMPERATURE,
    # ecoSOL specific device classes (ecoSOL [n] models)
    "T1": _SensorDeviceClass.TEMPERATURE,
    "T2": _SensorDeviceClass.TEMPERATURE,
    "T3": _SensorDeviceClass.TEMPERATURE,
    "T4": _SensorDeviceClass.TEMPERATURE,
    "T5": _SensorDeviceClass.TEMPERATURE,
    "T6": _SensorDeviceClass.TEMPERATURE,
    "TzCWU": _SensorDeviceClass.TEMPERATURE,
    "P1": None,
    "P2": None,
    "H": None,
    "Moc_chwilowa": _SensorDeviceClass.POWER,
    "Uzysk_ca_kowity": _SensorDeviceClass.ENERGY,
    # ecoSOL diagnostic device classes
    "ecosrvAddr": None,
    "softVer": None,
    "routerType": None,
    "protocolType": None,
    "controllerID": None,
    "ecosrvSoftVer": None,
}

# Number entity device classes
ENTITY_NUMBER_SENSOR_DEVICE_CLASS_MAP = {
    "tempCOSet": _NumberDeviceClass.TEMPERATURE,
    "tempCWUSet": _NumberDeviceClass.TEMPERATURE,
    # ecoMAX850R2-X specific number entities
    "mixerSetTemp5": _NumberDeviceClass.TEMPERATURE,
}

# Binary sensor device classes
ENTITY_BINARY_DEVICE_CLASS_MAP = {
    # By default all binary sensors device_class are RUNNING
    "mainSrv": _BinarySensorDeviceClass.CONNECTIVITY,
    "wifi": _BinarySensorDeviceClass.CONNECTIVITY,
    "lan": _BinarySensorDeviceClass.CONNECTIVITY,
    "fuelConsumptionCalc": _BinarySensorDeviceClass.RUNNING,
    "ecosrvHttps": _BinarySensorDeviceClass.CONNECTIVITY,
    # ecoMAX850R2-X specific binary sensors
    "contactGZC": _BinarySensorDeviceClass.CONNECTIVITY,
    "contactGZCActive": _BinarySensorDeviceClass.CONNECTIVITY,
    # Alarm sensors
    "alarmActive": _BinarySensorDeviceClass.PROBLEM,
}
