"""Entity state-class mappings."""

from homeassistant.components.sensor import SensorStateClass as _SensorStateClass

# Default state class for sensors not listed in STATE_CLASS_MAP. Numeric sensors
# inherit this so Home Assistant keeps long-term statistics; STATE_CLASS_MAP
# lists the keys to suppress to None.
DEFAULT_SENSOR_STATE_CLASS = _SensorStateClass.MEASUREMENT

# By default all sensors state_class are MEASUREMENT (see DEFAULT_SENSOR_STATE_CLASS)
STATE_CLASS_MAP: dict[str, _SensorStateClass | None] = {
    "lambdaStatus": None,
    "mode": None,
    "thermostat": None,
    "statusCO": None,
    "statusCWU": None,
    "softVer": None,
    "controllerID": None,
    "moduleASoftVer": None,
    "moduleBSoftVer": None,
    "moduleCSoftVer": None,
    "moduleLambdaSoftVer": None,
    "modulePanelSoftVer": None,
    # Diagnostic sensors (non-numeric)
    "routerType": None,
    "protocolType": None,
    "moduleEcoSTERSoftVer": None,
    "ecosrvSoftVer": None,
    "transmission": None,
    "ecoSterMode1": None,
    "ecoSterMode2": None,
    "ecoSterMode3": None,
    "ecoSterMode4": None,
    "ecoSterMode5": None,
    "ecoSterMode6": None,
    "ecoSterMode7": None,
    "ecoSterMode8": None,
    "P1": None,
    "P2": None,
    "H": None,
    "Moc_chwilowa": _SensorStateClass.MEASUREMENT,
    "Uzysk_ca_kowity": _SensorStateClass.TOTAL_INCREASING,
    # ecoMAX360i
    "PS": None,
    "heating_work_state_pump4": None,
    "flapValveStates": None,
    "HeatDemanded": None,
    "WaterPumpRunning": None,
    # ecoMAX360i informationParams / editParams sensors
    "FanSpeed": None,
    "COP": None,
    "SCOP": None,
    "FlowRate": None,
    "AXENREGISTER64": None,
    "AXENREGISTER65": None,
    # ecoMAX360i heat pump status sensors (not measurements)
    "HPStatusWorkMode": None,
    "HPStatusControl": None,
    "AxenUpperPump": None,
    "AxenWorkState": None,
    "ssaState": None,
    # Phoenix / extended heat-pump status sensors (not measurements)
    "Circuit1thermostat": None,
    "HPStatusBuffHeatStat": None,
    "HPStatusCircPStat0": None,
    "HPStatusCircPStat1": None,
    "HPStatusCircPStat2": None,
    "HPStatusCircPStat3": None,
    "HPStatusCircPStat4": None,
    "HPStatusCircPStat5": None,
    "HPStatusCircPStat6": None,
    "HPStatusFlowHeatStat": None,
    "HPStatusHdwHeatStat": None,
    "HPStatusUhsStat": None,
    "HP_work_state_set_pump2": None,
    "HP_work_state_set_pump3": None,
    "HP_work_state_set_pump4": None,
    "HP_work_state_set_pump5": None,
    # Phoenix / extended heat-pump measurements (numeric; explicit because the
    # default state_class is None to avoid bogus statistics on all-sensors keys).
    "BuforCalcSetTemp": _SensorStateClass.MEASUREMENT,
    "Circuit1CalcTemp": _SensorStateClass.MEASUREMENT,
    "Circuit2CalcTemp": _SensorStateClass.MEASUREMENT,
    "Circuit4CalcTemp": _SensorStateClass.MEASUREMENT,
    "Circuit5CalcTemp": _SensorStateClass.MEASUREMENT,
    "Circuit6CalcTemp": _SensorStateClass.MEASUREMENT,
    "Circuit7CalcTemp": _SensorStateClass.MEASUREMENT,
    "Circuit2thermostatTemp": _SensorStateClass.MEASUREMENT,
    "Circuit3thermostatTemp": _SensorStateClass.MEASUREMENT,
    "HDWsetpointcalculate": _SensorStateClass.MEASUREMENT,
    "HPStatusPresetTemp": _SensorStateClass.MEASUREMENT,
    "CoolingPower": _SensorStateClass.MEASUREMENT,
    "HeatingPower": _SensorStateClass.MEASUREMENT,
    "ElectricPower": _SensorStateClass.MEASUREMENT,
    "currentFlow": _SensorStateClass.MEASUREMENT,
    "TempBuforDown": _SensorStateClass.MEASUREMENT,
    "TempBuforUp": _SensorStateClass.MEASUREMENT,
    "TempCWU": _SensorStateClass.MEASUREMENT,
    "TempCircuit2": _SensorStateClass.MEASUREMENT,
    "TempCircuit3": _SensorStateClass.MEASUREMENT,
    "TempCircuit4": _SensorStateClass.MEASUREMENT,
    "TempCircuit5": _SensorStateClass.MEASUREMENT,
    "TempCircuit6": _SensorStateClass.MEASUREMENT,
    "TempCircuit7": _SensorStateClass.MEASUREMENT,
    "TempClutch": _SensorStateClass.MEASUREMENT,
    "TempWthr": _SensorStateClass.MEASUREMENT,
    "PHNXcoil_temp": _SensorStateClass.MEASUREMENT,
    "PHNXdischarge_temp": _SensorStateClass.MEASUREMENT,
    "PHNXinletTemp": _SensorStateClass.MEASUREMENT,
    "PHNXinletTemp_pump": _SensorStateClass.MEASUREMENT,
    "PHNXinletTemp_pump2": _SensorStateClass.MEASUREMENT,
    "PHNXinletTemp_pump3": _SensorStateClass.MEASUREMENT,
    "PHNXinletTemp_pump5": _SensorStateClass.MEASUREMENT,
    "PHNXoutletTemp": _SensorStateClass.MEASUREMENT,
    "PHNXoutletTemp_pump2": _SensorStateClass.MEASUREMENT,
    "PHNXoutletTemp_pump3": _SensorStateClass.MEASUREMENT,
    "PHNXoutletTemp_pump4": _SensorStateClass.MEASUREMENT,
    "PHNXoutletTemp_pump5": _SensorStateClass.MEASUREMENT,
    "PHNXreg2045": _SensorStateClass.MEASUREMENT,
    "PHNXreg2046": _SensorStateClass.MEASUREMENT,
    "PHNXreg2071": _SensorStateClass.MEASUREMENT,
    "PHNXreg2074": _SensorStateClass.MEASUREMENT,
    "PHNXsuctionTemp": _SensorStateClass.MEASUREMENT,
}
