"""Entity unit-of-measurement mappings."""

from homeassistant.const import (
    PERCENTAGE as _PERCENTAGE,
    SIGNAL_STRENGTH_DECIBELS_MILLIWATT as _SIGNAL_STRENGTH_DECIBELS_MILLIWATT,
    UnitOfEnergy as _UnitOfEnergy,
    UnitOfPower as _UnitOfPower,
    UnitOfTemperature as _UnitOfTemperature,
    UnitOfTime as _UnitOfTime,
)

from custom_components.econet300.const.core import SENSOR_FUEL_STREAM

# By default all sensors unit_of_measurement are None
ENTITY_UNIT_MAP = {
    "tempCO": _UnitOfTemperature.CELSIUS,
    "tempCOSet": _UnitOfTemperature.CELSIUS,
    "tempCWUSet": _UnitOfTemperature.CELSIUS,
    "tempExternalSensor": _UnitOfTemperature.CELSIUS,
    "tempFeeder": _UnitOfTemperature.CELSIUS,
    "lambdaLevel": _PERCENTAGE,
    "lambdaSet": _PERCENTAGE,
    "workAt100": _UnitOfTime.HOURS,
    "workAt50": _UnitOfTime.HOURS,
    "workAt30": _UnitOfTime.HOURS,
    "FeederWork": _UnitOfTime.HOURS,
    "thermoTemp": _UnitOfTemperature.CELSIUS,
    "fanPower": _PERCENTAGE,
    "tempFlueGas": _UnitOfTemperature.CELSIUS,
    "mixerSetTemp1": _UnitOfTemperature.CELSIUS,
    "mixerSetTemp2": _UnitOfTemperature.CELSIUS,
    "mixerSetTemp3": _UnitOfTemperature.CELSIUS,
    "mixerSetTemp4": _UnitOfTemperature.CELSIUS,
    "mixerSetTemp5": _UnitOfTemperature.CELSIUS,
    "mixerSetTemp6": _UnitOfTemperature.CELSIUS,
    "mixerTemp1": _UnitOfTemperature.CELSIUS,
    "mixerTemp2": _UnitOfTemperature.CELSIUS,
    "mixerTemp3": _UnitOfTemperature.CELSIUS,
    "mixerTemp4": _UnitOfTemperature.CELSIUS,
    "mixerTemp5": _UnitOfTemperature.CELSIUS,
    "mixerTemp6": _UnitOfTemperature.CELSIUS,
    "tempBack": _UnitOfTemperature.CELSIUS,
    "tempCWU": _UnitOfTemperature.CELSIUS,
    "boilerPower": _PERCENTAGE,
    "boilerPowerKW": _UnitOfPower.KILO_WATT,
    "fuelLevel": _PERCENTAGE,
    "tempUpperBuffer": _UnitOfTemperature.CELSIUS,
    "tempLowerBuffer": _UnitOfTemperature.CELSIUS,
    "signal": _SIGNAL_STRENGTH_DECIBELS_MILLIWATT,
    "quality": _PERCENTAGE,
    "valveMixer1": _PERCENTAGE,
    "burnerOutput": _PERCENTAGE,
    "mixerTemp": _UnitOfTemperature.CELSIUS,
    "mixerSetTemp": _UnitOfTemperature.CELSIUS,
    # ecoMAX850R2-X specific units
    "fuelConsum": _PERCENTAGE,
    SENSOR_FUEL_STREAM: "kg/h",  # Mass flow rate (confirmed from ecoNET cloud API)
    "transmission": None,
    # ecoSTER thermostat units
    "ecoSterTemp1": _UnitOfTemperature.CELSIUS,
    "ecoSterTemp2": _UnitOfTemperature.CELSIUS,
    "ecoSterTemp3": _UnitOfTemperature.CELSIUS,
    "ecoSterTemp4": _UnitOfTemperature.CELSIUS,
    "ecoSterTemp5": _UnitOfTemperature.CELSIUS,
    "ecoSterTemp6": _UnitOfTemperature.CELSIUS,
    "ecoSterTemp7": _UnitOfTemperature.CELSIUS,
    "ecoSterTemp8": _UnitOfTemperature.CELSIUS,
    "ecoSterSetTemp1": _UnitOfTemperature.CELSIUS,
    "ecoSterSetTemp2": _UnitOfTemperature.CELSIUS,
    "ecoSterSetTemp3": _UnitOfTemperature.CELSIUS,
    "ecoSterSetTemp4": _UnitOfTemperature.CELSIUS,
    "ecoSterSetTemp5": _UnitOfTemperature.CELSIUS,
    "ecoSterSetTemp6": _UnitOfTemperature.CELSIUS,
    "ecoSterSetTemp7": _UnitOfTemperature.CELSIUS,
    "ecoSterSetTemp8": _UnitOfTemperature.CELSIUS,
    "ecoSterMode1": None,
    "ecoSterMode2": None,
    "ecoSterMode3": None,
    "ecoSterMode4": None,
    "ecoSterMode5": None,
    "ecoSterMode6": None,
    "ecoSterMode7": None,
    "ecoSterMode8": None,
    # ecoMAX360i
    "Circuit2thermostatTemp": _UnitOfTemperature.CELSIUS,
    "Circuit3thermostatTemp": _UnitOfTemperature.CELSIUS,
    "Circuit4thermostatTemp": _UnitOfTemperature.CELSIUS,
    "Circuit5thermostatTemp": _UnitOfTemperature.CELSIUS,
    "Circuit6thermostatTemp": _UnitOfTemperature.CELSIUS,
    "Circuit7thermostatTemp": _UnitOfTemperature.CELSIUS,
    "TempClutch": _UnitOfTemperature.CELSIUS,
    "TempWthr": _UnitOfTemperature.CELSIUS,
    "TempCircuit2": _UnitOfTemperature.CELSIUS,
    "TempCircuit3": _UnitOfTemperature.CELSIUS,
    "TempCircuit4": _UnitOfTemperature.CELSIUS,
    "TempCircuit5": _UnitOfTemperature.CELSIUS,
    "TempCircuit6": _UnitOfTemperature.CELSIUS,
    "TempCircuit7": _UnitOfTemperature.CELSIUS,
    "TempBuforUp": _UnitOfTemperature.CELSIUS,
    "TempCWU": _UnitOfTemperature.CELSIUS,
    "TempBuforDown": _UnitOfTemperature.CELSIUS,
    "heatingUpperTemp": _UnitOfTemperature.CELSIUS,
    # Circuit1thermostat is a thermostat state (no "Temp" suffix), not a temperature.
    "Circuit1thermostat": None,
    "flapValveStates": None,
    "HeatDemanded": None,
    "WaterPumpRunning": None,
    # Heat pump (Axen) units
    "AxenOutdoorTemp": _UnitOfTemperature.CELSIUS,
    "AxenOutgoingTemp": _UnitOfTemperature.CELSIUS,
    "AxenReturnTemp": _UnitOfTemperature.CELSIUS,
    "AxenCompressorFreq": "Hz",
    "AxenUpperPump": None,
    "AxenWorkState": None,
    "HeatSourceCalcPresetTemp": _UnitOfTemperature.CELSIUS,
    # Heat pump compressor temperature units
    "afterCompressorTemp": _UnitOfTemperature.CELSIUS,
    "beforeCompressorTemp": _UnitOfTemperature.CELSIUS,
    "exhaustGasTemp": _UnitOfTemperature.CELSIUS,
    "outdoorTemp": _UnitOfTemperature.CELSIUS,
    # Heat pump status units
    "HPStatusWorkMode": None,
    "HPStatusPresetTemp": _UnitOfTemperature.CELSIUS,
    "HPStatusControl": None,
    # SSA (weather compensation) units
    "ssaState": None,
    "ssaCorr": _UnitOfTemperature.CELSIUS,
    "ssaPrevTemp": _UnitOfTemperature.CELSIUS,
    # Circuit comfort/eco temperature setpoints
    "Circuit1ComfortTemp": _UnitOfTemperature.CELSIUS,
    "Circuit1EcoTemp": _UnitOfTemperature.CELSIUS,
    "BufferTargetTemp": _UnitOfTemperature.CELSIUS,
    "Circuit2ComfortTemp": _UnitOfTemperature.CELSIUS,
    "Circuit2EcoTemp": _UnitOfTemperature.CELSIUS,
    "Circuit3ComfortTemp": _UnitOfTemperature.CELSIUS,
    "Circuit3EcoTemp": _UnitOfTemperature.CELSIUS,
    "Circuit4ComfortTemp": _UnitOfTemperature.CELSIUS,
    "Circuit4EcoTemp": _UnitOfTemperature.CELSIUS,
    "Circuit5ComfortTemp": _UnitOfTemperature.CELSIUS,
    "Circuit5EcoTemp": _UnitOfTemperature.CELSIUS,
    "Circuit6ComfortTemp": _UnitOfTemperature.CELSIUS,
    "Circuit6EcoTemp": _UnitOfTemperature.CELSIUS,
    "Circuit7ComfortTemp": _UnitOfTemperature.CELSIUS,
    "Circuit7EcoTemp": _UnitOfTemperature.CELSIUS,
    # ecoMAX360i informationParams / editParams sensors
    "TargetFlowTemp": _UnitOfTemperature.CELSIUS,
    "ActualFlowTemp": _UnitOfTemperature.CELSIUS,
    "ActualReturnTemp": _UnitOfTemperature.CELSIUS,
    "FanSpeed": "rpm",
    "HeatPumpAmbient": _UnitOfTemperature.CELSIUS,
    "ActualDHWTemp": _UnitOfTemperature.CELSIUS,
    "Circuit1DesiredLWT": _UnitOfTemperature.CELSIUS,
    "ElectricalPower": _UnitOfPower.KILO_WATT,
    "ThermalPower": _UnitOfPower.KILO_WATT,
    "COP": None,
    "SCOP": None,
    "FlowRate": "L/min",
    "AXENREGISTER64": None,
    "AXENREGISTER65": None,
    # Phoenix / extended heat-pump units (decomposed from EXTRA_SENSORS)
    "BuforCalcSetTemp": _UnitOfTemperature.CELSIUS,
    "Circuit1CalcTemp": _UnitOfTemperature.CELSIUS,
    "Circuit2CalcTemp": _UnitOfTemperature.CELSIUS,
    "Circuit4CalcTemp": _UnitOfTemperature.CELSIUS,
    "Circuit5CalcTemp": _UnitOfTemperature.CELSIUS,
    "Circuit6CalcTemp": _UnitOfTemperature.CELSIUS,
    "Circuit7CalcTemp": _UnitOfTemperature.CELSIUS,
    "HDWsetpointcalculate": _UnitOfTemperature.CELSIUS,
    "CoolingPower": _UnitOfPower.KILO_WATT,
    "HeatingPower": _UnitOfPower.KILO_WATT,
    "ElectricPower": _UnitOfPower.KILO_WATT,
    "currentFlow": "m³/h",
    "PHNXcoil_temp": _UnitOfTemperature.CELSIUS,
    "PHNXdischarge_temp": _UnitOfTemperature.CELSIUS,
    "PHNXinletTemp": _UnitOfTemperature.CELSIUS,
    "PHNXinletTemp_pump": _UnitOfTemperature.CELSIUS,
    "PHNXinletTemp_pump2": _UnitOfTemperature.CELSIUS,
    "PHNXinletTemp_pump3": _UnitOfTemperature.CELSIUS,
    "PHNXinletTemp_pump5": _UnitOfTemperature.CELSIUS,
    "PHNXoutletTemp": _UnitOfTemperature.CELSIUS,
    "PHNXoutletTemp_pump2": _UnitOfTemperature.CELSIUS,
    "PHNXoutletTemp_pump3": _UnitOfTemperature.CELSIUS,
    "PHNXoutletTemp_pump4": _UnitOfTemperature.CELSIUS,
    "PHNXoutletTemp_pump5": _UnitOfTemperature.CELSIUS,
    "PHNXreg2045": _UnitOfTemperature.CELSIUS,
    "PHNXreg2046": _UnitOfTemperature.CELSIUS,
    "PHNXreg2071": "Hz",
    "PHNXreg2074": "rpm",
    "PHNXsuctionTemp": _UnitOfTemperature.CELSIUS,
    # ecoSOL specific units (ecoSOL [n] models)
    "T1": _UnitOfTemperature.CELSIUS,
    "T2": _UnitOfTemperature.CELSIUS,
    "T3": _UnitOfTemperature.CELSIUS,
    "T4": _UnitOfTemperature.CELSIUS,
    "T5": _UnitOfTemperature.CELSIUS,
    "T6": _UnitOfTemperature.CELSIUS,
    "TzCWU": _UnitOfTemperature.CELSIUS,
    "P1": None,
    "P2": None,
    "H": None,
    "Moc_chwilowa": _UnitOfPower.KILO_WATT,
    "Uzysk_ca_kowity": _UnitOfEnergy.KILO_WATT_HOUR,
    # ecoSOL diagnostic units
    "ecosrvAddr": None,
    "softVer": None,
    "routerType": None,
    "protocolType": None,
    "controllerID": None,
    "ecosrvSoftVer": None,
    "moduleEcoSTERSoftVer": None,
}
