name: Bug Report
title: '"[Bug]: <short description>"'
description: Report an issue with Econet300 home assistant integration.
labels: ["bug", "triage"]
assignees: ["jontofront"]
body:
  - type: markdown
    attributes:
      value: >-
        This issue form is for reporting bugs only!
        If you have a feature or enhancement request, please use the feature request issue type.

  - type: textarea
    id: problem_description
    attributes:
      label: The problem
      description: Describe the issue you are experiencing here.
      placeholder: "Enter the problem description here"

  - type: checkboxes
    id: connected_devices
    attributes:
      label: Connected devices
      description: Select all ecoNET devices you have connected.
      options:
        - label: ecoMAX360
        - label: ecoMAX810P-L
        - label: ecoMAX850R2-X
        - label: ecoMAX860P2-N
        - label: ecoMAX860P3-V
        - label: ecoSOL 300
        - label: ecoSOL 500
        - label: SControl MK1
        - label: Other (please specify)

  - type: input
    id: device_model_other
    attributes:
      label: Other Device Model
      description: If you selected "Other", please specify your ecoNET device model here
      placeholder: "e.g., ecoMAX900P, ecoSOL300"

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How critical is this issue?
      options:
        - "Critical - System completely broken"
        - "High - Major functionality affected"
        - "Medium - Minor functionality affected"
        - "Low - Cosmetic or minor issue"

  - type: input
    id: econet300_version
    attributes:
      label: Current Version
      description: What version of Econet300 integration has the issue?
      placeholder: "Enter the version here"

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug.
      placeholder: "Enter the steps to reproduce the bug here"

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: "Enter the expected behavior here"

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: "Enter the actual behavior here"

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Include any relevant logs or error messages.
      placeholder: "Enter the logs or error messages here"

  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Core Version
      description: What version of Home Assistant Core has the issue?
      placeholder: "Enter the version here"

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics information
      placeholder: "Drag-and-drop diagnostics data file here"
      description: Follow HA guide to download diagnostic data. It would really help if you could download the diagnostics data for the device you are having issues with.
