name: Bug Report
title: '"[Bug]: <short description>"'
description: Report an issue with Econet300 home assistant integration.
labels: ["bug", "triage"]
assignees: ["jontofront"]
body:
  - type: markdown
    attributes:
      value: >-
        **Please describe the bug you found. The more details you provide, the faster we can help!**

  - type: textarea
    id: problem_description
    attributes:
      label: What's the problem? 🐛
      description: Describe what's not working as expected
      placeholder: "Example: The temperature sensor shows wrong values after restart"

  - type: checkboxes
    id: connected_devices
    attributes:
      label: Which ecoNET device do you have? 🔌
      description: Select your device (check all that apply)
      options:
        - label: ecoMAX360
        - label: ecoMAX810P-L
        - label: ecoMAX850R2-X
        - label: ecoMAX860P2-N
        - label: ecoMAX860P3-V
        - label: ecoSOL 300
        - label: ecoSOL 500
        - label: SControl MK1
        - label: Other (please specify)

  - type: input
    id: device_model_other
    attributes:
      label: Other Device Model
      description: If you selected "Other", what's your device model?
      placeholder: "e.g., ecoMAX900P"

  - type: dropdown
    id: severity
    attributes:
      label: How bad is it? 🚨
      description: Choose the severity level
      options:
        - "Critical - Nothing works"
        - "High - Major problem"
        - "Medium - Annoying but usable"
        - "Low - Minor issue"

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: How to reproduce? 📋
      description: Step-by-step instructions to see the bug
      placeholder: "1. Restart Home Assistant\n2. Check the sensor\n3. See wrong value"

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots 📸
      description: Add screenshots showing the problem (drag & drop images here)
      placeholder: "Upload screenshots of error messages, wrong values, or broken UI"

  - type: input
    id: versions
    attributes:
      label: Versions 📦
      description: What versions are you using?
      placeholder: "HA: 2025.2.2, Integration: v1.1.6"

  - type: textarea
    id: additional_info
    attributes:
      label: Anything else? 💡
      description: Additional details, logs, or context that might help
      placeholder: "Optional: logs, error messages, or other relevant info"
